// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xezguwrhbtykodxqniux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhlemd1d3JoYnR5a29keHFuaXV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMTQ3NDQsImV4cCI6MjA3Mzc5MDc0NH0.BkJ_bv7d_MweQ9Rg3MD4762haQCtU6DRBrJLvbFMkUs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});